# Generated by Django 3.1.7 on 2021-07-06 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210706_0418'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='Contact_us',
        ),
    ]
